export enum PAGES {
  NAV = 'nav',
  LOGIN = 'login',
  REGISTER = 'register',
  PROFILE = 'profile',
  CHANGE_PROFILE_DATA = 'change_profile_data',
  CHANGE_PROFILE_PASSWORD = 'change_profile_password',
  EMPTY_CHAT = 'empty_chat',
  CURRENT_CHAT = 'current_chat',
  CHAT_SEARCH_RESULTS = 'chat_search_results',
  CHANGE_AVATAR = 'change_avatar',
  LOADED_FILE = 'loaded_file',
  ON_LOAD_ERROR = 'on_load_error',
  ADD_USER = 'add_user',
  DELETE_USER = 'delete_user',
  ERROR_404 = 'error_404',
  ERROR_500 = 'error_500',
}
